# Generated by Django 6.0.5 on 2026-05-15 08:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('email_messages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('original_url', models.TextField()),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_clicked', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_tokens', to='email_messages.message')),
            ],
            options={
                'verbose_name': 'Click Token',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpenToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_opened', models.DateTimeField(blank=True, null=True)),
                ('last_opened', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_tokens', to='email_messages.message')),
            ],
            options={
                'verbose_name': 'Open Token',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('unsubscribed', 'Unsubscribed'), ('failed', 'Failed')], db_index=True, max_length=15)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('clicked_url', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='email_messages.message')),
            ],
            options={
                'verbose_name': 'Message Event',
                'verbose_name_plural': 'Message Events',
                'ordering': ['occurred_at'],
                'indexes': [models.Index(fields=['message', 'event_type'], name='events_mess_message_7f9ad5_idx'), models.Index(fields=['message', 'occurred_at'], name='events_mess_message_e3a99f_idx'), models.Index(fields=['event_type', 'occurred_at'], name='events_mess_event_t_001920_idx')],
            },
        ),
    ]
