# Generated by Django 6.0.5 on 2026-05-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_messages', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clicktoken',
            name='first_clicked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='clicktoken',
            index=models.Index(fields=['token'], name='events_clic_token_90783c_idx'),
        ),
        migrations.AddIndex(
            model_name='opentoken',
            index=models.Index(fields=['token'], name='events_open_token_a67794_idx'),
        ),
    ]
