# Generated by Django 6.0.5 on 2026-05-15 08:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
        ('templates_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('to_email', models.EmailField(db_index=True, max_length=254)),
                ('to_name', models.CharField(blank=True, max_length=255)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=998)),
                ('body_html', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('failed', 'Failed')], db_index=True, default='queued', max_length=12)),
                ('esp_message_id', models.CharField(blank=True, help_text='Message ID returned by the ESP (SES, Mailgun, etc.)', max_length=255)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('next_attempt', models.DateTimeField(blank=True, null=True)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='domains.domain')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='templates_app.emailtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_no', models.PositiveSmallIntegerField()),
                ('success', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('esp_response', models.JSONField(blank=True, default=dict)),
                ('attempted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='email_messages.message')),
            ],
            options={
                'verbose_name': 'Message Attempt',
                'verbose_name_plural': 'Message Attempts',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user', 'status'], name='email_messa_user_id_ee217f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user', 'created_at'], name='email_messa_user_id_d8938e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['to_email'], name='email_messa_to_emai_3f08f2_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['esp_message_id'], name='email_messa_esp_mes_3a9663_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messageattempt',
            unique_together={('message', 'attempt_no')},
        ),
    ]
