# Generated by Django 6.0.5 on 2026-05-13 09:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Bare domain: example.com (no https://)', max_length=253, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('spf_verified', models.BooleanField(default=False)),
                ('spf_last_check', models.DateTimeField(blank=True, null=True)),
                ('dkim_selector', models.CharField(default='mf1', max_length=63)),
                ('dkim_private_key', models.TextField(blank=True, help_text='PEM-encoded RSA private key (never exposed via API)')),
                ('dkim_public_key', models.TextField(blank=True, help_text='Base64 DER public key – placed in DNS TXT record')),
                ('dkim_verified', models.BooleanField(default=False)),
                ('dkim_last_check', models.DateTimeField(blank=True, null=True)),
                ('dmarc_verified', models.BooleanField(default=False)),
                ('dmarc_last_check', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='domains_dom_name_96e6f6_idx'), models.Index(fields=['user', 'status'], name='domains_dom_user_id_209c24_idx')],
            },
        ),
    ]
