# Generated by Django 6.0.5 on 2026-05-14 08:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsubscribeToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('message_id', models.UUIDField(blank=True, null=True)),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unsubscribe_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unsubscribe Token',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Suppression',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('email_hash', models.CharField(editable=False, help_text='SHA-256 of the lowercase email for fast lookup', max_length=64)),
                ('reason', models.CharField(choices=[('bounce', 'Hard Bounce'), ('complaint', 'Spam Complaint'), ('unsubscribe', 'Unsubscribed'), ('manual', 'Manually Added')], db_index=True, default='manual', max_length=15)),
                ('source_message_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional admin note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suppression',
                'verbose_name_plural': 'Suppressions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'email_hash'], name='suppression_user_id_2f19fb_idx'), models.Index(fields=['user', 'reason'], name='suppression_user_id_93de62_idx')],
                'unique_together': {('user', 'email_hash')},
            },
        ),
    ]
