# Generated by Django 6.0.5 on 2026-05-15 14:16

import django.db.models.deletion
import django.utils.timezone
import secrets
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('url', models.URLField(help_text='HTTPS endpoint URL', max_length=2048)),
                ('secret', models.CharField(default=secrets.token_hex, help_text='HMAC-SHA256 signing secret — expose once via API on creation', max_length=64)),
                ('event_types', models.JSONField(blank=True, default=list, help_text='Event types to deliver. Empty = all events.')),
                ('is_active', models.BooleanField(default=True)),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('failed_deliveries', models.PositiveIntegerField(default=0)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=20)),
                ('message_id', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('attempt_no', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('attempted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Round-trip time in milliseconds', null=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.webhook')),
            ],
            options={
                'verbose_name': 'Webhook Delivery',
                'verbose_name_plural': 'Webhook Deliveries',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['user', 'is_active'], name='webhooks_we_user_id_51012d_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['webhook', 'status'], name='webhooks_we_webhook_322278_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['webhook', 'attempted_at'], name='webhooks_we_webhook_5ecf4b_idx'),
        ),
    ]
