# Generated by Django 6.0.5 on 2026-05-14 08:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, help_text="Machine-readable identifier for use in the API (e.g. 'welcome-email')", max_length=200)),
                ('subject', models.CharField(help_text='Email subject line. Supports Jinja2 variables: {{ first_name }}', max_length=998)),
                ('body_type', models.CharField(choices=[('html', 'HTML'), ('mjml', 'MJML'), ('text', 'Plain Text')], default='html', max_length=5)),
                ('body_html', models.TextField(blank=True, help_text='HTML body. Use Jinja2 syntax for dynamic content.')),
                ('body_mjml', models.TextField(blank=True, help_text='MJML source. Compiled to body_html automatically on save.')),
                ('body_text', models.TextField(blank=True, help_text='Plain-text fallback. Auto-generated from HTML if left blank.')),
                ('is_active', models.BooleanField(default=True)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('variable_schema', models.JSONField(blank=True, default=dict, help_text='Declared template variables and their descriptions.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=998)),
                ('body_html', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('body_mjml', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='templates_app.emailtemplate')),
            ],
            options={
                'verbose_name': 'Template Version',
                'verbose_name_plural': 'Template Versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['user', 'is_active'], name='templates_a_user_id_9cf296_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['slug'], name='templates_a_slug_7bebb6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together={('user', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='templateversion',
            unique_together={('template', 'version_number')},
        ),
    ]
