# Generated by Django 6.0.5 on 2026-05-21 12:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('sent', models.PositiveIntegerField(default=0)),
                ('delivered', models.PositiveIntegerField(default=0)),
                ('opened', models.PositiveIntegerField(default=0)),
                ('clicked', models.PositiveIntegerField(default=0)),
                ('bounced', models.PositiveIntegerField(default=0)),
                ('complained', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('unsubscribed', models.PositiveIntegerField(default=0)),
                ('open_rate', models.FloatField(default=0.0)),
                ('click_rate', models.FloatField(default=0.0)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('complaint_rate', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_stats', to='domains.domain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Stat',
                'verbose_name_plural': 'Daily Stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='analytics_d_user_id_d5275f_idx'), models.Index(fields=['user', 'domain', 'date'], name='analytics_d_user_id_6ce054_idx')],
                'unique_together': {('user', 'domain', 'date')},
            },
        ),
    ]
