# Generated by Django 6.0.5 on 2026-05-13 09:23

import apps.authentication.models
import django.db.models.deletion
import django.utils.timezone
import pyotp
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64)),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(default=apps.authentication.models._token_expiry)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret', models.CharField(default=pyotp.random_base32, help_text='Base32 TOTP secret – never expose in API responses', max_length=64)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'TOTP Device',
            },
        ),
        migrations.AddField(
            model_name='apikey',
            name='rate_limit_per_hour',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='rate_limit_per_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='prefix',
            field=models.CharField(editable=False, help_text='First 12 chars of the raw key shown in the dashboard', max_length=12),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('api_key_created', 'API Key Created'), ('api_key_revoked', 'API Key Revoked'), ('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('password_reset', 'Password Reset'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled'), ('domain_added', 'Domain Added'), ('domain_verified', 'Domain Verified'), ('template_edited', 'Template Edited')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key_hash'], name='authenticat_key_has_886d1f_idx'),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='totpdevice',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp_device', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backupcode',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to='authentication.totpdevice'),
        ),
    ]
